### ISSUE TITLE
🐛 :: Fork가 안되용

### ISSUE THREAD

**Issue by Haesus** [TOVBUS/ColorChips#115]
## 🐞 버그 설명
레포 가져와서 보고 싶은데...

## 🧐 원했던 기능
포크가 안되용...

## 📸 스크린샷
뀨잉...

## ⚙️ 작업 환경
 - 도구: 예) Xcode 15.4
 - 환경: 예) 아이폰 15 Pro
 - OS 버전: 예) iOS 17.1

## ➕ 추가 설명
이 문제에 대한 추가 설명이 있다면 적어주세요.

**Comment by doyeonjeong** [comment]
@Haesus Public으로 방금 열었는데 이제 되는지 함 봐주실래여!?

**Comment by Haesus** [comment]
오 fork 잘 됩니다. LGTM👍
